services:
  aichart:
    image: addmangroup/smart-chart:latest
    container_name: smart-chart
    build: .
    restart: unless-stopped
    env_file: .env
    ports:
      - 4018:4018 # Frontend
      - 4019:4019 # API

# docker buildx build --push -t addmangroup/smart-chart:latest .