services:
  aichart:
    image: addmangroup/smart-chart:latest
    container_name: smart-chart
    build: .
    restart: unless-stopped
    env_file: .env.prod
    ports:
      - 4848:4018 # Frontend (external:internal)
      - 4019:4019 # API

# docker buildx build --push -t addmangroup/smart-chart:latest .